all: ./data ./data/registrations_2019.csv

./data:
	mkdir -p data

./data/registrations_2015.csv:
	curl -L -k -o $@ "https://sdi.eea.europa.eu/datashare/s/rBr6krg8YFKgwHC/download?path=&files=CO_vans_v16.csv"
./data/registrations_2016.csv:
	curl -L -k -o $@ "https://sdi.eea.europa.eu/datashare/s/rBr6krg8YFKgwHC/download?path=&files=CO_vans_v16.csv"
./data/registrations_2017.csv:
	curl -L -k -o $@ "https://sdi.eea.europa.eu/datashare/s/rBr6krg8YFKgwHC/download?path=&files=CO_vans_v16.csv"
./data/registrations_2018.csv:
	curl -L -k -o $@ "https://sdi.eea.europa.eu/datashare/s/rBr6krg8YFKgwHC/download?path=&files=CO_vans_v16.csv"
./data/registrations_2019.csv:
	curl -L -k -o $@ "https://sdi.eea.europa.eu/datashare/s/rBr6krg8YFKgwHC/download?path=&files=CO_vans_v16.csv"
